Try to speed up typecheck step by installing less stuff

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,23 +12,26 @@ jobs:
 
       - uses: astral-sh/setup-uv@v7
 
-      - name: Install Python dependencies + setup virtualenv
+      - name: Install basedpyright
         run: |
-          uv sync --dev
+          uv tool install basedpyright
+
+      - name: Setup virtualenv
+        run: |
           uv venv fullinstallenv
           VIRTUAL_ENV=fullinstallenv uv pip install .
 
       - name: Run basedpyright
         run: |
-          uv run basedpyright --pythonpath fullinstallenv/bin/python --level=error $(fullinstallenv/bin/python -c 'import apitofsim; import os; print(os.path.dirname(apitofsim.__file__))')
+          basedpyright --pythonpath fullinstallenv/bin/python --level=error $(fullinstallenv/bin/python -c 'import apitofsim; import os; print(os.path.dirname(apitofsim.__file__))')
 
       - name: Run basedpyright with warnings
         run: |
-          uv run basedpyright --pythonpath fullinstallenv/bin/python $(fullinstallenv/bin/python -c 'import apitofsim; import os; print(os.path.dirname(apitofsim.__file__))')
+          basedpyright --pythonpath fullinstallenv/bin/python $(fullinstallenv/bin/python -c 'import apitofsim; import os; print(os.path.dirname(apitofsim.__file__))')
 
       - name: Run basedpyright coverage
         run: |
-          uv run basedpyright --pythonpath fullinstallenv/bin/python --verifytypes apitofsim || true # Ignore failures for now
+          basedpyright --pythonpath fullinstallenv/bin/python --verifytypes apitofsim || true # Ignore failures for now
 
   lint_python:
     name: Style check Python
